services:

  ssh-clean:
    build:
      context: ./ssh-clean
    container_name: ssh-clean
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      - transform
    cap_add:
      - IPC_LOCK
    tty: true
    stdin_open: true
    privileged: true

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
networks:
  transform:

volumes:
  mysql_data:  