services:

  traefik:
    image: traefik:3.4.1
    restart: unless-stopped
    command:
      - --api.insecure=true          
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"     
      - "8081:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - transform

  wordpress:
    image: wordpress:6.8.1
    restart: unless-stopped
    env_file:
      - ./wordpress/.env  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=PathPrefix(`/wp`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.middlewares.wordpress-stripprefix.stripprefix.prefixes=/wp"
      - "traefik.http.routers.wordpress.middlewares=wordpress-stripprefix@docker"
    networks:
      - transform

  mysql:
    image: mariadb:11.8.2
    restart: unless-stopped
    env_file:
      - ./mariadb/.env   
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - transform

  ssh-clean:
    build:
      context: ./ssh-clean
    container_name: ssh-clean
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      - transform
    cap_add:
      - IPC_LOCK
    tty: true
    stdin_open: true
    privileged: true     
    
networks:
  transform:

volumes:
  mysql_data: