services:

  ssh-clean:
    build:
      context: ./ssh-clean
    container_name: ssh-clean
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      - transform
    cap_add:
      - IPC_LOCK
    tty: true
    stdin_open: true
    privileged: true     
    
networks:
  transform: